/**
 * List of all available photo paths.
 * To add a new photo:
 * 1. Place the image in /public/photos/ (e.g., jl5.JPEG)
 * 2. Add the path to this array.
 */
export const photos = [
  '/photos/lj1.JPEG',
  '/photos/lj2.JPEG',
  '/photos/lj3.JPEG',
  '/photos/lj4.JPEG',
  '/photos/lj5.JPEG',
  '/photos/lj6.JPEG',
  '/photos/lj7.JPEG',
  '/photos/lj8.JPEG',
  '/photos/lj9.JPEG',
  '/photos/lj10.JPEG',
  '/photos/lj11.JPEG',
  '/photos/lj12.JPEG',
  '/photos/lj13.JPEG',
  '/photos/lj14.jpg',
  '/photos/lj15.jpg',
  '/photos/lj16.jpg',
  '/photos/lj17.jpg',
  '/photos/lj18.jpg',
  '/photos/lj19.jpg',
  '/photos/lj20.jpg',
  '/photos/lj21.jpg',
  '/photos/lj22.jpg',
  '/photos/lj23.jpg',
  '/photos/lj24.jpg',
  '/photos/lj25.jpg',
  '/photos/lj26.jpg',
  '/photos/lj27.jpg',
  '/photos/lj28.jpg',
  '/photos/lj29.jpg',
  '/photos/lj30.jpg',
  '/photos/lj31.jpg',
  '/photos/lj32.jpg',
  '/photos/lj33.jpg',
  '/photos/lj34.jpg',
  '/photos/lj35.jpg',
  '/photos/lj36.jpg',
  '/photos/lj37.jpg',
  '/photos/lj38.jpg',
  '/photos/lj39.jpg',
  '/photos/lj40.jpg',
  '/photos/lj41.jpg',
  '/photos/lj42.jpg',
  '/photos/lj43.jpg',
  '/photos/lj44.jpg',
];

